// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Fruitnesia",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Fruitnesia",
            targets: ["AppModule"],
            bundleIdentifier: "com.evelyn.salakku",
            teamIdentifier: "86T9R8CK49",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            capabilities: [
                .photoLibraryAdd(purposeString: "We want to save the card to your photos library")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)